version: "3"

services:
  demo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: demo:latest
    volumes:
       - ./demo/log:/app/demo/log
    environment:
      - FIZZ=${FIZZ}
      - API_KEY_WEATHER=${API_KEY_WEATHER}
      - REMOTE_URL=${REMOTE_URL}

networks:
  default:
    external:
      name: selenium_hub
